name: Build topic feeds

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: feeds-build
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm ci
      - run: npm run build:feeds
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: 'chore(feeds): refresh topic feeds'
          body: 'Automated feed refresh from CI.'
          commit-message: 'chore(feeds): refresh topic feeds'
          branch: feeds/refresh-${{ github.run_id }}
          delete-branch: true
          committer: feed-bot <feed-bot@users.noreply.github.com>
          author: feed-bot <feed-bot@users.noreply.github.com>
