name: Build topic feeds

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm ci
      - run: npm run build:feeds
      - name: Commit feeds
        run: |
          git config user.name "feed-bot"
          git config user.email "feed-bot@users.noreply.github.com"
          git add public/feeds/*.json || true
          git diff --cached --quiet || git commit -m "chore(feeds): refresh topic feeds"

      - name: Push changes (force-with-lease)
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
          force: true
