name: Build topic feeds

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run build:feeds
      - name: Commit feeds
        run: |
          git config user.name "feed-bot"
          git config user.email "feed-bot@users.noreply.github.com"
          git add public/feeds/*.json
          git diff --cached --quiet && echo "No changes" || git commit -m "chore(feeds): refresh topic feeds"
          git push

