name: Build topic feeds

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: feeds-build
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm ci
      - run: npm run build:feeds
      - name: Commit and push feeds
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: chore(feeds): refresh topic feeds
          file_pattern: public/feeds/*.json
          branch: ${{ github.ref_name }}
          commit_user_name: feed-bot
          commit_user_email: feed-bot@users.noreply.github.com
          push_options: --force-with-lease
